### ISSUE TITLE
Unable to install via NPM

### ISSUE THREAD

**Issue by keogblem** [GrafiteInc/Helpers#3]
Hi,
I am getting trouble when trying to install it with NPM.

`The authenticity of host 'github.com (140.82.118.3)' can't be established.`

Is somebody getting the same error ? And how can we solve that ?
Thanks

**Comment by tairau** [comment]
@keogblem try `yarn add @grafite/helpers` or `npm i  @grafite/helpers`

**Comment by keogblem** [comment]
It works !
Thanks @Tairau 👍 

Hope the package owner will update the README installation section
